#!/usr/bin/python3

from editor import main
import argparse

if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("file", nargs="?", help="file to open in Quark")
  parser.add_argument("--debug", action="store_true", help="run Quark in debug mode")
  args = parser.parse_args()
  main(args)
